language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run build
  - npm test